ERIP = "https://raschet.by/about/novosti/uvedomleniya/"
BFT = "https://www.bfn.by/category/tehnicheskie-raboty/"
BPC = "https://www.npc.by/news/"
MNS = "https://nalog.gov.by/news/?category=%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B"
OAIS = "https://nces.by/o-nas/news/"
A1 = "https://support.a1.by/planovye-tekhnicheskie-raboty/"
MTS = "https://www.mts.by/help/obsluzhivanie/raboty-na-seti/"
Life = "https://life.com.by/network-works"
Seventech = "https://seven.tech/ru/novosti/"
Beltelecom = "https://beltelecom.by/calendar-field_network_date/month"
Delova9Seti = "https://bn.by/news/tekhnicheskie-raboty/"
Hoster = "https://hoster.by/clients/news/"
BeCloud = "https://becloud.by/customers/informing/"
Oplati = "https://www.o-plati.by/news"
Kupala = "https://kupala.by/press_tsentr/"
BVFB = "https://bcse.by/press-center"
NBRB = "https://www.nbrb.by/news"
WhiteBird = "https://whitebird.io/news"
Bank_AlfaRu = "https://alfabank.ru/news/t/release/"
Bank_Belarusbank = "https://belarusbank.by/be/33139/press/technical-works"
Bank_BSB = "https://www.bsb.by/novosti-bsb-banka"
Bank_BTA = "https://neobank.by/about/news/"
Bank_BankReshenii = "https://rbank.by/news/?filter=all"
Bank_BELWEB = "https://www.belveb.by/notifications/"
Bank_BelAgro = "https://www.belapb.by/"
Bank_Belinvest = "https://www.belinvestbank.by/about-bank/press-service/news"
Bank_MTB = "https://www.mtbank.by/about/news/"
Bank_Paritet = "https://www.paritetbank.by/about/notifications/"
Bank_Zepter = "https://www.zepterbank.by/bank/newsroom/news/"
Bank_Sberbank = "https://www.sber-bank.by/page/press-news"
Bank_Priorbank = "https://www.priorbank.by/priorbank-main/press-center/news"



