ERIP = "https://raschet.by/about/novosti/uvedomleniya/"
BFT = "https://www.bfn.by/category/tehnicheskie-raboty/"
BPC = "https://www.npc.by/news/"
MNS = "https://nalog.gov.by/news/?category=%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5+%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B"
OAIS = "https://nces.by/o-nas/news/"
A1 = "https://support.a1.by/planovye-tekhnicheskie-raboty/"
MTS = "https://www.mts.by/help/obsluzhivanie/raboty-na-seti/"
Life = "https://life.com.by/network-works"
Seventech = "https://seven.tech/ru/novosti/"
Beltelecom = "https://beltelecom.by/calendar-field_network_date/month"
Delova9Seti = "https://bn.by/news/tekhnicheskie-raboty/"
Hoster = "https://hoster.by/clients/news/"
BeCloud = "https://becloud.by/customers/informing/"
Oplati = "https://www.o-plati.by/news"

Kupala = ""
BVFB = ""
NBRB = ""
Bank_AlfaRu = ""
Bank_Belarusbank = ""
Bank_BSB = ""
Bank_BTA = ""
Bank_BankReshenii = ""
Bank_BELWEB = ""
Bank_BelAgro = ""
Bank_Belinvest = ""
Bank_MTB = ""
Bank_Paritet = ""
Bank_Zepter = ""
Bank_Sberbank = ""



